package client;

public enum MenuOptions {
    ADD_TO_CART, REMOVE_FROM_CART, VIEW_CART, PURCHASE_ITEMS, VIEW_ITEMS, LOGOUT, // For customer
    VIEW_ITEMS_ADMIN, ADD_ITEM, REMOVE_ITEM, UPDATE_ITEM, ADD_ADMIN, ADD_CUSTOMER, REMOVE_CUSTOMER, LOGOUT_ADMIN // For admin
}